- operations/README.md
- operations/customers.md
- operations/enterprises.md
- operations/reservations.md
- operations/services.md
```
* Extended [Company](operations/enterprise.md#company) with `TaxIdentifier`,  `TaxIdentificationNumber` is deprecated. 
* Extended [Company](operations/enterprise.md#company) with `AccountingCode`.
* Extended [Add customer](operations/customers.md#add-customer) and [Update customer](operations/customers.md#update-customer) with `Identity card`, `Visa`, `Drivers license`.
* Added [Update reservation customer](operations/reservations.md#update-reservation-customer).
```
> New features in connector API

- websockets.md
If accepted, please remove Youtrack issue TDR-146
> Update websockets.md hotlinks

- operations/finance.md
```
* Extended [Bill](operations/finance.md#bill) with `CounterId`.
```
> Counter Id in bill Dto.

- operations/integrations.md
```
* Extended [Key cutter command data](operations/integrations.md#key-cutter-command-data) with `Telephone` and `ReservationNumber`.
```
> Key cutter command data update.

- operations/README.md
- operations/enterprises.md
Added [Get all outlets](operations/enterprises.md#get-all-outlets) operation.
> Get all outlets

- operations/README.md
- operations/finance.md
* Added [Add outlet bills](operations/finance.md#add-outlet-bills) operation.
> Add outlets bills

- operations/reservations.md
```
* Extended [Get all reservations](operations/reservations.md#get-all-reservations) with possibility to retrieve notes.
```
> June extensions.

- operations/README.md
- operations/customers.md
```
* Added [Get all customers by name](operations/customers.md#get-all-customers-by-name) operation.
```
> Get all customers by name

- operations/reservations.md
```
* Extended [Add reservations](operations/reservations.md#add-reservations) with possibility to turn the rate applicability check off.
```
> Ignore rate applicability

- operations/reservations.md
Fixed Connector API documentation to add to Reservation/add new parameter "CheckOverbooking".
> Add CheckOverbooking to AddReservations

- operations/README.md
- operations/finance.md
Add documentation for a new method Get outlet items/bills in Connector API
> Get outlet items

- operations/configuration.md
- operations/enterprises.md
- operations/finance.md
- operations/integrations.md
```
* [Get all countries](operations/configuration.md#get-all-countries) extended with [CountrySubdivisions](operations/configuration/md#country-subdivision) and [CountryAlliances](operations/configuration.md#country-alliance).
* [Get all space blocks](operations/enterprises.md#get-all-space-blocks) extended with [TimeFilter](operations/enterprises.md#space-block-time-filter).
* [Get all accounting items](operations/finance.md#get-all-accounting-items) extended with [Accounting item extent](operations/finance.md#accounting-item-extent) and [Credit card transactions](operations/finance.md#credit-card-transaction).
* [Key cutter command data](operations/integrations.md#key-cutter-command-data) with `Email`.
```
> Batch documentation update.

- operations/README.md
- operations/integrations.md
- operations/reservations.md
```
* Extended [Add reservations](operations/reservations.md#add-reservations) parameters with `GroupId`.
* Added [Confirm reservation](operations/reservations.me#confirm-reservation) operation.
* Extended [Payment terminal command data](operations/integrations.md#payment-terminal-command-data) with `PaymentTerminalData`.
```
> Reservations doc update

- operations/enterprises.md
```
Extended [Space category](operations/enterprises.md#space-category) with `ExtraUnitCount`.
```
> Extra unit count added

- operations/enterprises.md
- operations/reservations.md
```
* Extended [Add reservations](operations/reservations.md#add-reservations) parameters with `ReleasedUtc`.
* Extended [Company](operations/enterprises.md#company) with `Number`.
```
> Connector api update 

- operations/customers.md
Integrators could accidentally overwrite Mewsers own guest profile notes.
> Clarify notes field limitations

- operations/services.md
```
* Extended [Service](operations/services.md#service) with `Type`.
```
> Service type

- operations/enterprises.md
```
* Extended [Space feature](operations/enterprises.md#space-feature) with `Names`, `ShortName`, `ShortNames`, `Descriptions`.
```
> Space feature translations

- operations/reservations.md
Added to reservation documenation information about QrCode data
> QR code in get reservations

- operations/reservations.md
```
* Extended [Add reservations](operations/reservations.md#add-reservations) parameters with `TimeUnitCost`.
```
> TimeUnitCost for new reservation

- operations/reservations.md
```
* Extended [Add reservations](operations/reservations.md#add-reservations) parameters with `TravelAgencyId`.
```
> TravelAgencyId in reservations add

- operations/finance.md
```
* Extended [Bill](operations/finance.md#bill) with `VariableSymbol`.
```
> Variable symbol

- operations/customers.md
```
* Extended [Add customer](operations/customers.md#add-customer) parameters with `Options`.
* Extended [Update customer](operations/customers.md#add-customer) parameters with `Options`.
```
- Documentation wasn't updated when the options were added.
> Customers extended with Options.

- operations/README.md
- operations/enterprises.md
```
* Added [Get all companies by name](operations/enterprises.md#get-all-companies-by-name) operation.
```
> Companies by name

- operations/README.md
- operations/finance.md
```
* Added [Charge credit card](operations/finance.md#charge-credit-card) operation.
```
> Charge credit card

- operations/reservations.md
```
* Extended [Add reservations](operations/reservations.md#add-reservations) parameters with `CompanyId`.
```
> CompanyId in `Add Reservations.`

- operations/enterprises.md
```
* Extended [Company](operations/enterprises.md#company) with `IsActive`.
```
> Extended Company with IsActive.

- guidelines.md
- operations/README.md
- operations/services.md
TPD-5031 Added documentation for General Restrictions API: Base & Rates
> General Restrictions API documentation

- operations/enterprises.md
```
* Extended [Get all space blocks](operations/enterprise.md#get-all-space-blocks) parameters with `Extent`.
* Extended [Space block](operations/enterprise.md#space-block) with `IsActive`.
```
> Space block update

- operations/enterprises.md
Add `public string BillingCode { get; set; }` in Company in Connector.
> Extended company response with billing code

- operations/README.md
- operations/reservations.md
> #TDR-650 Fixed

- changelog.md
Updated spelling Match to March.
> Guideline modification

- operations/services.md
Adding the new product charging enums as reserved for future use. this will be announced in same email as the usa api once merged
> Updating product charging enums

- changelog.md
- operations/README.md
- operations/configuration.md
- operations/customers.md
- operations/finance.md
- operations/integrations.md
- operations/reservations.md
- operations/services.md
* Additions required for the Italian fiscal printer
* USA API changes
> Fiscal additions

- operations/reservations.md
missing commas in json reservation/add
> missing commas in json reservation/add

- operations/finance.md
External payment type extended.
> documentation: External payment type extended

- operations/reservations.md
reservations/add and reservations/update extended of booker info
> documentation-booker

- operations/reservations.md
moved booker parameter closer to customer
> booker below customer

- operations/README.md
- operations/finance.md
Merged when MewsSystems/mews#13521 deployed
> Get all bills

- operations/finance.md
Missing sentence describing bills
> Missing sentence in bills/getAll

- operations/customers.md
customers extended of billing code and accounting code
merge after https://github.com/MewsSystems/mews/pull/14157
> customers extended of billing code and accounting code

- operations/README.md
- operations/enterprises.md
```
* Added [Update company](operations/enterprises.md#udpate-company) operation.
```
> Update company added

- changelog.md
- operations/configuration.md
updated documentation based on this https://github.com/MewsSystems/gitbook-connector-api/pull/91
> PaymentCardStorage extension

- operations/services.md
Introduced product posting
```
```
> Introduced ProductPosting

- operations/README.md
- operations/enterprises.md
https://mews.myjetbrains.com/youtrack/issue/TDR-1763
```
* Added spaceBlocks/delete to operation overview
* Added spaceBlocks/delete request/response to enterprises.md
```
> Add spaceBlocks/delete

- operations/enterprises.md
> Rename Time Interval

- operations/services.md
```
* Extended [Get all products](operations/services.md#get-all-products) result with `Classifications` property.
```
> Added product classification

- README.md
- webhooks.md
```
* Webhooks usage added.
```
> Webhooks documentation

- operations/enterprises.md
```
* Extended [Get all spaces](operations/enterprises.md#get-all-spaces) `SpaceFeatures` result with `Classification` property.
```
> Add space feature classification

- operations/finance.md
- operations/reservations.md
```
* Updated definition of [Accounting item](operations/finance.md#accounting-item) and [Get all reservation items](operations/reservations.md#get-all-reservation-items) operation.
```
> Updates accounting items definition

- operations/enterprises.md
```
* Modified spaces/getAll
```
> Removed SpaceCategories extent default

- operations/reservations.md
```
* Updated [Add reservations](operations/reservations.md#add-reservations) operation to accept `Enquired` state.
```
> Allow Enquired in reservation/add

- operations/finance.md
```
* Extended [Get all cashier transactions](operations/finance.md#get-all-cashier-transactions) parameters with `CreatedUtc` time filter.
```
> New time filters cashierTransactions/getAll

- operations/README.md
- operations/enterprises.md
```
* Added new operation [Get all tasks](operations/enterprises.md#get-all-tasks).
```
> New operation tasks/getall

- webhooks.md
```
* Amended Webhooks documentation
```
As per [previous PR](https://github.com/MewsSystems/gitbook-connector-api/pull/118#pullrequestreview-365888638)
> Webhooks fix

- operations/integrations.md
* internal change of the structure.
> New command structure

- operations/customers.md
- operations/enterprises.md
- operations/finance.md
- operations/reservations.md
- operations/services.md
* All extents are now required. The user has to specify that data will be sent.
> Extent is required

- operations/README.md
- operations/reservations.md
```
* Extended [Get all reservations](https://mews-systems.gitbook.io/connector-api/operations/reservations#get-all-reservations) with `ReservationIds`, `GroupIds`, `CustomerIds`.  Extended [Confirm reservations](https://mews-systems.gitbook.io/connector-api/operations/reservations#confirm-reservation), [Cancel reservations](https://mews-systems.gitbook.io/connector-api/operations/reservations#cancel-reservation), [Update reservation interval](https://mews-systems.gitbook.io/connector-api/operations/reservations#update-reservation-interval) & [Update reservation](https://mews-systems.gitbook.io/connector-api/operations/reservations#update-reservation) to support multiple `ReservationIds`. 
```
> group management reservation updates

- operations/finance.md
```
* Fixed the description of the value of TaxValues in the Amount Value
```
> Singularize the TaxValues contents

- operations/customers.md
```
* Added missing gender fields and added default values in example code
```
> Add missing gender fields

- operations/reservations.md
> update pr 146

- changelog.md
> log of recent changes

- guidelines.md
> credentials update

- operations/services.md
New property ExternalName added to Get all rates.
```
```
> externalName added to rates get all

- operations/configuration.md
> tax rate strategy update based on discriminated unions

- operations/services.md
```
* Extended operation [Get all restrictions](operations/services.md#get-all-restrictions) with parameters `BaseRateIds` and `ExactRateIds`.
```
> update restriction filtering

- operations/README.md
- operations/configuration.md
- operations/customers.md
```
* Added new operation [Get all accounting environments](operations/configuration.md#get-all-accounting-environments).
* Extended operations [Add customer](operations/customers.md#add-customer) and [Update customer](operations/customers.md#update-customer) with parameter `LegalIdentifiers`.
```
> Customer legal identifiers

- operations/README.md
- operations/finance.md
```
* Added operations `accountingItems/update`, `bills/add` and `bills/delete`
```
> Billing API part 1

- operations/README.md
- operations/enterprises.md
- operations/finance.md
```
* Added operations [Get all counters](operations/enterprises.md#get-all-counters), [Close bill](operations/finance.md#close-bill), [Get bill PDF](operations/finance.md#get-bill-pdf)
```
> Billing API part2

- operations/finance.md
```
* Updated parameters for [Close bill](operations/finance.md#close-bill) operation.
```
> update Bill close

- operations/services.md
```
* Extended operations [Get all products](operations/services.md#get-all-products) with property `ExternalName`.
```
> Add ExternalName products/getAll

- operations/reservations.md
- operations/services.md
```
* Extended [Product order parameters](operations/services.md#Product order parameters) with consuption dates.
```
> consuption dates

- operations/README.md
```
* Fixed operation overview after introducing resources.
```
> spacetime update operation overview

- operations/configuration.md
- operations/services.md
- webhooks.md
* Extended [Get configuration](operations/configuration.md#get-configuration) response with [Service](operations/services#service).
* Extended [Integration created data](webhooks#integration-created-data) with [Service](webhooks#service).
> service updates

- operations/enterprises.md
```
* Extended [Travel agency contract](operations/enterprises#travel-agency-contract) with `ServiceId`
```
> Added service to travel agency contract

- operations/services.md
```
* Extended [Promotions](operations/services.md#promotions) object with `DuringCheckOut` property.
```
> Add DuringCheckOut promotion

- operations/finance.md
```
* Extended [Bill](operations/finance.md#bill) object with [Bill assignee data](operations/finance.md#bill-assignee-data).
```
> Extended bill serialization

- operations/enterprises.md
```
* Extended [Resource](operations/enterprises#resource) with `CreatedUtc` and `UpdatedUtc`
* Extended [Resource category assignment](operations/enterprises#resource-category-assignment) with `Id`, `IsActive`, `CreatedUtc` and `UpdatedUtc`
* Extended [Resource category image assignment](operations/enterprises#resource-category-image-assignment) with `Id`, `IsActive`, `CreatedUtc` and `UpdatedUtc`
* Extended [Resource feature assignment](operations/enterprises#resource-feature-assignment) with `Id`, `IsActive`, `CreatedUtc` and `UpdatedUtc`
```
> Extended resource dtos

- operations/README.md
- operations/finance.md
```
* Added new operation [Add alternative payment](operations/finance.md#add-alternative-payment).
```
> Added payments/addAlternative documentation

- operations/README.md
- operations/services.md
```
* Added new operation [Get all rules](operations/services.md#rules).
```
> Product rules

- operations/finance.md
```
* Updated new operation [Get all accounting items](operations/finance.md#Get-all-accounting-items).
```
!!! Please don't merge it yet until https://github.com/MewsSystems/mews/pull/19452 and  https://github.com/MewsSystems/mews/pull/19628 and deployed !!!
> Updated accountingItem getAll endpoint

- websockets.md
```
* Replaced Space websocket event by [Resource event](websockets.md#resource-event)
* Extended [Reservation event](websockets.md#reservation-event) with `AssignedResourceId`
* Extended [Price update event](websockets.md#price-update-event) with `ResourceCategoryId`
```
> Websockets resource updates

- operations/services.md
> Fixed resource category type on restriction

- operations/services.md
> clarify orders/add

- operations/README.md
- operations/services.md
```
* Added operation [Update service availability](operations/services.md#update-service-availability).
```
> update availability operation

- operations/reservations.md
```
* Extended operation [Update reservation](operations/reservations.md#update-reservation) with parameter `AssignedResourceLocked`.
```
> add unlock reservation

- operations/configuration.md
```
* Extended response of operation [Get all tax environments](operations/configuration.md#get-all-tax-environments) with validity interval of taxation.
```
> add tax validity interval

- operations/services.md
```
* Extended operation [Get service availability](operations/services.md#get-service-availability) with list of active availability adjustments.
```
> Serialize availabilty adjustments

- operations/finance.md
- operations/reservations.md
> accounting item state updates

- operations/configuration.md
> Fix tax validity interval

- operations/README.md
- operations/enterprises.md
- operations/reservations.md
- operations/services.md
```
* Added operation [Get all vouchers](operations/services.md#get-all-vouchers) and extended  [Reservation](operations/reservations.md#reservation) with property `VoucherId`.
```
> Voucher codes

- operations/reservations.md
```
* Extended operation [Get all reservations](operations/reservations.md#get-all-reservations) with property `CancellationReason`.
```
> Add cancellation reason

- operations/configuration.md
```
* Improved description of parameter for operation [Get all tax environments](operations/configuration.md#get-configuration).
```
> Better explanation of tax codes

- operations/customers.md
```
* Extended operation [Get all customers](operations/customers.md#get-all-customers) with property `LoyaltyCodes`.
```
> Add loyalty codes

- operations/configuration.md
> CR of tax rate explanation

- guidelines.md
based on: https://mews.myjetbrains.com/youtrack/issue/RND-43741
It might also be helpful to include some intro text under `### Request limits`, not sure how we should say it. 
sample:
"There are limits to how many API requests you can send in a given 15-minute interval. If you have reached the limit, you can expect the HTTP code `429` and should retry after 15 minutes" 
```
```
> add request limits

- operations/reservations.md
> Revert cancellation reason

- operations/enterprises.md
```
* Extended [Space resource data](operations/enterprises.md#space-resource-data) with `LocationNotes`.
* Extended [Space resource data update](operations/enterprises.md#space-resource-data-update) with `LocationNotes`.
```
> Added location details to the Resource

- websockets.md
```
* Changed the [websocket](websockets.md) authentication method to use cookies instead of URL query parameters.
```
> Cookie based auth

- websockets.md
based on https://github.com/MewsSystems/gitbook-connector-api/pull/220#discussion_r547246639
> Extend cookie description

- operations/reservations.md
> Update reservation CR

- operations/finance.md
Based on https://github.com/MewsSystems/gitbook-connector-api/pull/223#pullrequestreview-562069550
> Subtype list formatting

- operations/customers.md
- operations/enterprises.md
- operations/finance.md
- operations/integrations.md
- operations/reservations.md
- operations/services.md
```
* Specified limitations on operation parameters (generally 1000 items in collection and maximum time filter length of 3 months).
```
> Add limitations

- guidelines.md
- operations/configuration.md
- operations/customers.md
- operations/enterprises.md
- operations/finance.md
- operations/integrations.md
- operations/reservations.md
- operations/services.md
- webhooks.md
- websockets.md
> Rename column to Contract

- changelog.md
- guidelines.md
1) moved request limits to sit under Request section rather than under Response section.
2) taxations
3) add changelog
```
*  
```
> request limit in correct section + taxation

- operations/configuration.md
```
* Split `taxEnvironments/getAll` and `taxations/getAll`
* Added TaxationCodes to TaxEnvironment and removed TaxEnvironmentCode from Taxation
* Extended TaxRate discriminator with Dependent
```
> Updated Taxation documentation

- operations/services.md
```
* Added [Add availability blocks](operations/services.md#add-availability-blocks), [Delete availability blocks](operations/services.md#delete-availability-blocks).
* Extended [Update service availability](operations/services.md#update-service-availability) with `AvailabilityBlockId`.
```
> Availability blocks

- operations/configuration.md
- operations/finance.md
```
* Added note about amount precision.
```
> Add info about amount precision

- operations/README.md
- operations/reservations.md
- operations/services.md
```
* Added new operation [Get all availability blocks](operations/services.md#get-all-availability-blocks) to retrieve availability blocks.
* Extended operation [Add availability blocks](operations/services.md#add-availability-blocks) with properties `RateId` and `ExternalIdentifier`.
* Extended operations [Add reservation](operations/reservations.md#add-reservation) and [Update reservation](operations/reservations.md#update-reservation) with property `AvailabilityBlockId`.
```
> Availability blocks update

- webhooks.md
```
* Introduced new format of [General webook message](#webhooks.md/general-message) used for notifying about reservation changes.
```
> Reservation webhook

- operations/reservations.md
- operations/services.md
- webhooks.md
> Unified format of reservations

- operations/services.md
> Availabilty block rename

- use-cases/point-of-sale.md
Updated use case based on questions received from integration partners. Added link to Mews Glossary. Rephrased some passive sentences. Fixed some tiny typos. 
```
```
> update POS use case + clarifications

- operations/enterprises.md
```
* Extended counters/getAll with bill preview counters.
```
> Extended counters/getAll with bill preview counters

- operations/README.md
- operations/services.md
```
* Added [Get all resource access tokens](operations/services.md#get-all-resource-access-tokens), [Add resource access tokens](operations/services.md#add-resource-access-tokens), [Update resource access tokens](operations/services.md#update-resource-access-tokens), [Delete resource access tokens](operations/services.md#delete-resource-access-tokens)
```
> Resource access token documentation

- operations/reservations.md
```
Extended operation [Process reservation](operations/reservations.md#process-reservation) with list of check out conditions.
```
> Add Check Out conditions

- guidelines.md
```
* Extended API response codes with `408` request timeout.
```
> add timeout

- operations/reservations.md
```
* Removed obsolete property `CompanionIds` from [Reservation](operations/reservations.md#reservation) surpassed by operation [Get all companionships](operations/services.md#get-all-companionships).
```
> remove companionIds

- operations/services.md
Update the docs so it stays consistent between all operations.
[schema.json.zip](https://github.com/MewsSystems/gitbook-connector-api/files/6151294/schema.json.zip)
> Update docs so it stays consistent

- guidelines.md
- websockets.md
```
* Platform demo environment URL changed to `https://api.mews-demo.com`.
* Web socket platform demo environment URL changed to `https://ws.mews-demo.com`.
```
https://mews.myjetbrains.com/youtrack/issue/RND-51839
> Demo urls changed.

- operations/finance.md
> Improve creditCards/addTokenized 

- webhooks.md
```
* Added new type `ResourceUpdated` of webhook [Event](webhooks.md#event).
```
> Add resource webhook event

- operations/finance.md
> Extend Accounting category classification

- operations/customers.md
```
* Extended [Customer](operations/customers.md#customer) with property `CompanyId`.
```
> Added companyId to customer

- operations/reservations.md
```
* Extended [Reservation](operations/reservations.md#reservation-parameters) with property `VoucherCode`.
```
> Added VoucherCode to reservation

- use-cases/point-of-sale.md
> correct typo in POS test case

- use-cases/README.md
- use-cases/event-management.md
```
* Extended use case with availability block endpoints 
* added description for using the billing endpoints (add bill, close bill, update accounting items)
* included Kiosk use case in the Use case README.md file so that it appears in Gitbook
```
> Event management use case - include availability blocks, billing endpoints

- operations/services.md
```
* Extended [Get all availability blocks](operations/services.md#get-all-availability-blocks) parameters with `CreatedUtc` and `UpdatedUtc`.
```
> Availability filters

- operations/services.md
```
* Extended [Add availability block](operations/services.md#availability-block-parameters) parameters with `Name`, `VoucherCode`, `Budget`, `ReservationPurpose`, `Notes`.
```
> Availability blocks add parameters

- use-cases/revenue-management.md
I think it should not be mentioned in the change log @vitasamek ?
```
* Removed occupancy times from RMS use case
```
> Removed occupancy interval from RMS use case

- operations/services.md
- use-cases/event-management.md
it's now not possible to delete availability blocks - updated description to align with current system behaviour.
```
```
> update description of delete availability block behaviour

- operations/services.md
```
* Fixed example request in [Add availability blocks](services/customers.md#add-availability-blocks)
```
> Fix format of availabilityBlocks/add

- operations/customers.md
```
* Extended `customers/search` endpoint with the `Extents` 
```
> update customers search extent

- websockets.md
> Websocket authentication without spaces

- operations/README.md
- operations/services.md
```
* Added [Update availability blocks](operations/services.md#update-availability-blocks) operation.
```
> Update availability blocks added

- operations/services.md
Reverts MewsSystems/gitbook-connector-api#272
> Revert "specify number value requirements in orders add"

- guidelines/taxation.md
missing ``` in the multi-tax environments section
```
```
> fix formatting in taxation.md

- operations/finance.md
```
* Document changes in [Get all accounting items](operations/finance.md#get-all-accounting-items) operation.
```
Changes in other related endpoints will be a separate PR due to scope of changes.
> Document changes in accountingItems/getAll

- operations/customers.md
> Fixed customers/getOpenItems example

- changelog.md
- guidelines/requests.md
team is consolidating email addresses and keeping only partnersuccess@mews.com
```
```
> change contact email address

- operations/services.md
```
* Extended [Availability block parameters](operations/services.md#availability-block-parameters) with State.
```
> AddAvailabilityBlocks state field

- operations/reservations.md
```
* mention the requirement in the add reservation endpoint
* extent event management use case with information on how to handle this
* link the two together
```
> document requirements for reservations in availability blocks

- operations/reservations.md
Reservations/add and Reservations/update: Re-wrote the descriptions for parameters 'CheckRateApplicability' and 'CheckOverbooking' to better explain what these parameters are.
```
```
> Update reservations.md (YouTrack RND-40712)

- guidelines/environments.md
> url updated

- changelog.md
- operations/finance.md
```
* Removed BillOptions.Rebated
```
> Removed BillOptions.Rebated

- operations/README.md
- operations/services.md
```
* Added [Get all age categories](operations/services.md#get-all-age-categories) operation.
```
> Get all age category introduced.

- operations/finance.md
- operations/reservations.md
- operations/services.md
```
* Extended [Update availability blocks](operations/services.md#update-availability-blocks) with other properties to update.
```
> Extend update availability blocks endpoint

- operations/enterprises.md
aims to answer this question (which has a response from Jiri)
https://stackoverflow.com/c/mews-systems/questions/7948
this is the current logic applied to extents in the reservations/getAll endpoint - only those associated to the reservation fetched are returned.
```
```
> update get all resources description

- operations/services.md
update the endpoint description to answer the question --> get rate pricing - what price does it return? Gross or Net? 
```
```
> update rate pricing endpoint description

- operations/accountingitems.md
- operations/agecategories.md
Product order item data extended with AgeCategoryId
> Extend  Product order item data documentation

- guidelines/communicate.md
- webhooks/README.md
> Webhooks changes

- operations/companies.md
```
* Extended operations [Get all companies](../operations/companies.md#get-all-companies) with `Options` property.
* Extended operations [Add companies](../operations/companies.md#add-companies) with `Options` property.
* Extended operations [Update companies](../operations/companies.md#update-companies) with `Options` property.
```
> Extended company endpoints with options

- webhooks/wh-general.md
```
* Extended webhook [Supported events](../webhooks/wh-general.md#supported-events) with AddedMessages.
```
> MessageAdded webhook

- operations/bills.md
> Fix Order Item and Payment Item links

- guidelines/requests.md
- guidelines/responses.md
- operations/README.md
```
* Added guidelines around handling 408 errors
```
> Added guidelines around handling 408 errors

- deprecations/README.md
```
* Deprecations page re-designed
```
> Re-designed Deprecations page

- changelog/README.md
- deprecations/README.md
- operations/README.md
- operations/availabilityblocks.md
- operations/rates.md
> Release develop into master

- guidelines/environments.md
```
* Added statement about [whitelisting](../guidelines/environments.md#whitelisting)
```
> Added paragraph about whitelisting

- changelog/README.md
- operations/reservations.md
```
* [Update reservations](../operations/reservations.md#update-reservations) Added Purpose update field
```
> Added Purpose parameter to the reservations/update operation.

- SUMMARY.md
- changelog/README.md
- guidelines/README.md
- guidelines/pagination.md
```
* Added new page [Pagination](../guidelines/pagination.md) under [Guidelines](../guidelines/README.md)
```
> added new pagination page under guidelines

- changelog/README.md
- operations/bills.md
- operations/outletitems.md
- operations/reservations.md
```
* [Get all reservation](../operations/reservations.md#get-all-reservations) Added Limitation and Cursor
* [Get all bills](../operations/bill.md#get-all-bills) Added Limitation and Cursor
* [Get all outletItems](../operations/outletitems.md#get-all-outletitems) Added Limitation and Cursor
```
> Added limitation to bills, outletItems, reservations

- changelog/README.md
- guidelines/pagination.md
- operations/messages.md
- operations/messagethreads.md
> Unify pagination across operations

- .github/PULL_REQUEST_TEMPLATE.md
> Update changelog flow

- changelog/README.md
- webhooks/wh-general.md
> Resource blocks webhook

- changelog/README.md
- operations/availabilityblocks.md
> Added CompanyId for GetAll AvailabilityBlocks

- changelog/README.md
- operations/customers.md
[KANBAN-1633](https://mews.myjetbrains.com/youtrack/issue/kanban-1633) : Updated Customer object with ActivityState and MergeTargetId
> Added a ActivityState and MergeTargetId into the [Customer] entity.

- changelog/README.md
- deprecations/README.md
- webhooks/wh-general.md
> Implemented new Customer webhooks

- changelog/README.md
- operations/customers.md
Extended `Customers/getAll` response with `CarRegistrationNumber`
> Added CarRegistrationNumber field for Customers GetAll

- changelog/README.md
- operations/companycontracts.md
Extended travel agency contract response with new fields and reorder them.
Added travel agency contract options section.
> Extended travel agency contract

- changelog/README.md
- operations/resourceaccesstokens.md
Implement pagination for Customer "resourceAccessTokens/getAll"
- [ x ] The changelog and potentially a deprecation entries are in place.
- [ x ] JSON example extended.
- [ x ] New properties in the table are added to the correct place.
- [ x ] Correct formatting:
> Limitation for resource access tokens

- changelog/README.md
- operations/README.md
- operations/loyaltyprograms.md
Updated Loyalty Programs operation with add, update, delete.
> Add remaining operations for loyalty programs

- changelog/README.md
- operations/companies.md
Extended companies.md with add and update fields for NCH.
Extended changelog accordingly. 
> Extended companies.md with add and update fields

- changelog/README.md
- operations/accountingitems.md
Extended accountingitems/getall response with UnitCount and UnitAmount.
> Extended accountingitems/getall response with UnitCount and UnitAmount

- changelog/README.md
- operations/outletbills.md
- operations/outletitems.md
Extended outlet items with 1 field from [here ](https://github.com/MewsSystems/mews/pull/37002).
> Extended the outlet items with external identifier

- changelog/README.md
- operations/products.md
* Added cursor pagination in `Get All Products`.
* Extended `Get all products` with `CustomerProducts`.
> Extend products get all

- changelog/README.md
- operations/loyaltymemberships.md
Added Added primary and points to LoyaltyMembership and extended getAll/add/update operations
> Added primary and points to LoyaltyMembership

- SUMMARY.md
- changelog/README.md
- operations/README.md
- operations/routingrules.md
Added documentation for all routing rule operations.
> Routing rules

- SUMMARY.md
- changelog/README.md
- deprecations/README.md
- operations/README.md
- operations/accounts.md
- operations/customers.md
Added new endpoint `accounts/merge` and deprecated old `customers/merge`.
> Accounts merge

- changelog/README.md
- changelog/changelog2022.md
- operations/bills.md
Extended bill documentation with bill enterprise data
> Added documentation for enterprise data in bill

- changelog/README.md
- operations/products.md
Added a single property AccountingCategoryId to Product.
> Add accounting category id in product

- operations/README.md
1. **Address** section removed and Address-related operations placed under **Accounts**
2. **Customers (guests)** changed to just **Customers**
> small tidying up of operations page

- changelog/README.md
- changelog/changelog2023.md
- operations/addresses.md
A documentation update for https://github.com/MewsSystems/mews/pull/38834
> Addresses get all by updated utc

- SUMMARY.md
- changelog/README.md
- operations/README.md
- operations/serviceorders.md
Created a documentation for `serviceOrderNotes/getAll`
> Service order notes get all

- changelog/README.md
- deprecations/README.md
- operations/companies.md
Added enterpriseIdentifiers filters and limitation to the companies/getAll
> Companies pagination and external identifiers

- changelog/README.md
- operations/companies.md
Added option to add and update ExternalIdentifier in company endpoints.
> Added option to add and update ExternalIdentifier in company endpoints

- README.md
- SUMMARY.md
- deprecations/README.md
API Docs improvement initiatives - miscellaneous small changes:
1. Welcome page titled "Mews Connector API" not "Introduction"
2. Welcome page unnecessary paragraph removed
3. Welcome page edited wording around OpenAPI definition
4. Deprecations page added link to Deprecations Policy
> API Docs improvement initiatives - miscellaneous small changes

- changelog/README.md
- operations/availabilityblocks.md
Added UpdatedUtc filter to Get all availability blocks.
> add UpdatedUtc filter to Get all availability blocks

- changelog/README.md
- operations/accountingitems.md
added filtering through updated utc to the endpoint AccountingItems/getall
> docs accountingItems extension

- changelog/README.md
- operations/bills.md
- operations/companionships.md
added filtering through updated utc to the endpoint companionships/getall
> Updated utc companionships

- changelog/README.md
- operations/outletitems.md
- operations/sources.md
Added new filtering and extended response to `sources/getAll` and `outletItems/getAll`
> Sources and OutletItems

- changelog/README.md
- operations/sourceassignments.md
Added ability to filter UpdatedUtc for s`ourceassignments/getall`
> UpdatedUtc for source assignments

- changelog/README.md
- operations/configuration.md
Added accounting configuration for the Enterprise containing financial information about the property.
> AccountingConfiguration for enterprise

- changelog/changelog2023.md
- operations/README.md
- operations/restrictions.md
Add restrictions set operation
> Restrictions set operation

- SUMMARY.md
- changelog/README.md
- getting-started/README.md
- guidelines/README.md
- guidelines/best-practices.md
* Added new page 'Best practises' to Guidelines section
* Referenced new page from 'Getting started' page
* Referenced new page from 'Guidelines' home page
> added new Best practises page

- changelog/README.md
- changelog/changelog2023.md
- operations/README.md
- operations/restrictions.md
> Restrictions clear operation

- operations/bills.md
- operations/companies.md
- operations/resourceblocks.md
- operations/services.md
> fix bills heading

- changelog/README.md
- deprecations/README.md
- operations/accountingitems.md
> Original amount

- SUMMARY.md
- changelog/README.md
- operations/README.md
- operations/enterprises.md
Added a portfolio-enabled endpoint description to fetch basic enterprise data (https://github.com/MewsSystems/mews/pull/41612).
> add enterprises page with get-all

- operations/README.md
- operations/orderitems.md
- operations/payments.md
Mark payments/getAll and orderItems/getall as restricted
> Mark payments/getAll and orderItems/getall as restricted

- operations/loyaltymemberships.md
> Fix missing comma

- SUMMARY.md
- changelog/README.md
- operations/README.md
- operations/cancellationpolicies.md
added docs for newly implemented endpoint:
https://github.com/MewsSystems/mews/pull/42124
> cancellation policies get all new operation

- SUMMARY.md
- changelog/README.md
- operations/README.md
- operations/reservationgroups.md
added new operation `reservationGroups/getall`
> documentation for reservationGroups/getall

- operations/README.md
- operations/loyaltymemberships.md
- operations/loyaltyprograms.md
- operations/loyaltytiers.md
Removing loyalty restrictions as it's removed in the code.
Code change [PR](https://github.com/MewsSystems/mews/pull/43233) is merged - ✔️ 
> Remove loyalty operation restrictions

- changelog/README.md
- operations/loyaltymemberships.md
Extended LoyaltyMembership with State.
> Extend LoyaltyMembership with State

- changelog/README.md
- operations/orders.md
> add BillId to orders/add

- operations/orderitems.md
- operations/payments.md
Remove restricted from both endpoints.
> Remove restricted from orderItems/getall and payments/getAll

- operations/customers.md
> Add  "IssuingCity" to the documents section

- changelog/README.md
- operations/bills.md
Addition of Name property to connector api documentation
> Addition of Name property to connector api documentation

- operations/restrictions.md
We changed the behaviour so that:
- Connector only manages restrictions created by Integration
- Commander only manages restrictions created by User...
This means, that user can have defined restrictions that sit alongside the ones created by Integration ...
> Restrictions set/clear affected restrictions

- SUMMARY.md
- changelog/README.md
- operations/README.md
- operations/accountnotes.md
Added documentation for all operations concerning account notes
> Added documentation for account notes

- use-cases/payment-automation/using-tokenized-credit-cards.md
* Edited the "Using tokenized credit cards" page because of changes to the PCI Proxy site
* No Changelog entry because no new functionality as such
* Ref. [Asana ](https://app.asana.com/0/1201871773388036/1205007894632051/f)
> updated Using tokenized credit cards to fix broken PCI Proxy links

- changelog/README.md
- operations/bills.md
- operations/commands.md
added docs for bills/close bills/delete commands/addprinter commands/addkeycutter
> docs for bills/close bills/delete commands/addprinter commands/addkeycutter

- changelog/README.md
- operations/README.md
- operations/payments.md
> Payments refund

- changelog/README.md
- use-cases/kiosk.md
* Re-wrote the Kiosk use case, especially to clarify payment options
* As requested by Ria and Charlie
> re-wrote the Kiosk use case

- changelog/README.md
- operations/customers.md
> Added new customer classifications

- changelog/README.md
- operations/customers.md
- operations/reservations.md
https://mews.atlassian.net/browse/CON-103
> Docs extension to portfolio

- changelog/README.md
- operations/availabilityblocks.md
Added portfolio support docs to availability blocks /add, /update and /delete operations. Also modified /update operation response as it now returns an updated entity list instead of empty response.
This documents changes from these PRs:
https://github.com/MewsSystems/mews/pull/44400
https://github.com/MewsSystems/mews/pull/45271
> Availability blocks portfolio + /update response

- changelog/README.md
- operations/messages.md
- operations/messagethreads.md
Update documentation for `messages/getAll` and `messageThreads/getAll` with portfolio support.
> CON-233: Add portfolio to messages, messageThreads

- operations/reservations.md
> Fixed response struct PersonCounts - Count type

- changelog/README.md
- operations/README.md
- operations/products.md
> Add products/delete operation

- changelog/README.md
- operations/counters.md
Removed 'AccountingCounter' type from Counter Type Discriminator as it will never get returned.
> Update of counters.md documentation

- operations/rates.md
> Fix headers

- changelog/README.md
- guidelines/pagination.md
* Clarified when cursor is null in the response
* Added small section on how to request pages
> Updated pagination page to clarify how to request pages

- changelog/README.md
- operations/accountingcategories.md
- operations/agecategories.md
- operations/businesssegments.md
- operations/cashiers.md
- operations/companycontracts.md
- operations/configuration.md
- operations/counters.md
- operations/creditcards.md
- operations/departments.md
- operations/enterprises.md
- operations/outlets.md
- operations/paymentrequests.md
- operations/products.md
- operations/resourceaccesstokens.md
- operations/routingrules.md
- operations/rules.md
- operations/services.md
Added filtering by `UpdatedUtc` for some operations + extended response with `CreatedUtc` and `UpdatedUtc`.
> Added UpdatedUtc filters

- changelog/README.md
> Fix changelog

- SUMMARY.md
- changelog/README.md
- deprecations/README.md
- operations/README.md
- operations/_objects.md
- operations/vouchercodes.md
- operations/vouchers.md
> Voucher and voucher codes endpoints

- operations/vouchers.md
> Fix voucher type type

- changelog/README.md
- operations/customers.md
> added student classification

- changelog/README.md
- operations/orders.md
Enable Portfolio Access Token for orders/add operation.
> CON-630: Enable Portfolio Access Token for orders/add

- SUMMARY.md
- changelog/README.md
- operations/README.md
- operations/exports.md
Add reference for exports operations:
- `exports/getAll`
- `exports/add`
> CON-461: Add reference for Exports operations

- changelog/README.md
- operations/payments.md
Added new external payment type option to payments/addExternal request.
> add DepositWireTransfer payment type

- changelog/README.md
- operations/orderitems.md
Extended order item type with Tax correction type
> Extended order item type with Tax correction type

- changelog/README.md
- deprecations/README.md
- operations/bills.md
Updated documentation to reflect changes under new company billing.
> bills changes

- changelog/README.md
- operations/reservations.md
Extended reservation update with options.
> Reservation update options

- operations/bills.md
> Updated response example

- changelog/README.md
- operations/availabilityadjustments.md
- operations/availabilityblocks.md
> Add updatedUtc field to availability adjustment

- operations/serviceordernotes.md
After testing the endpoint i figured out it does support PAT. 
I dont have access to the style guide, but i have followed other examples.
> Update serviceordernotes.md with PAT support

- changelog/README.md
- deprecations/README.md
- operations/products.md
> feat: update documentation for the new product localized properties

- changelog/README.md
- operations/payments.md
Added one more external payment type to Add external payment operation.
> Add Twint external payment type

- changelog/README.md
- operations/exports.md
Added customer and company export entities.
> Add customer and company export entities

- operations/addresses.md
> updated response payload to include UpdatedUtc and isActive flag on addresses

- operations/productserviceorders.md
- operations/reservations.md
> Profile fix description

- changelog/README.md
- operations/reservations.md
> Fixed errors in reservations/getAll/2023-06-06

- changelog/README.md
- operations/rates.md
- operations/vouchers.md
> ExternalIdentifiers for vouchers/getall and rates/getall

- changelog/README.md
- deprecations/README.md
Pushed back discontinued dates for [deprecated features](../deprecations/README.md)
> Postpone dicontinued dates

- SUMMARY.md
> Fix summary

- changelog/README.md
- operations/orderitems.md
> Added options for the order item

- SUMMARY.md
- changelog/README.md
- use-cases/README.md
- use-cases/how-to.md
* Added new 'how to' use cases page
> Added new 'how to' use cases page

- changelog/README.md
- operations/resourcecategories.md
Added activity states for resourceCategories/getall
> Activity states for resourceCategories

- use-cases/events.md
* Corrected two instances of broken links for 'Get all products'
* Changed "bookable service" to "Additional Service" in section 'Adding revenue and payment items'
> corrected a couple of minor errors in the Events use case

- changelog/README.md
- operations/reservations.md
Added filtering by ScheduledStartUtc for Reservation (ver 2023-06-06)
> ScheduledStartUtc for Reservation (ver 2023-06-06)

- changelog/README.md
- operations/reservations.md
* Removed unused reservation state `Requested` (confirmed by Reservations team)
> removed unused reservation state 'Requested'

- deprecations/README.md
> Push back discontinuation date on accountingItems/getAll

- changelog/README.md
- operations/commands.md
- operations/orders.md
- operations/productserviceorders.md
> Added linked reservation id to product service orders.

- changelog/README.md
- deprecations/README.md
- operations/payments.md
Introduces `Data` and deprecates `Method` and `RedirectUrl` parameters for `payments/addAlternative` request.
> FINTECH-2470 - adds Data into payments/addAlternative

- changelog/README.md
- operations/creditcards.md
Missed this endpoint when extended doc regarding the linking payments to reservations.
> Extended credit card charge endpoint with ReservationId

- changelog/README.md
- operations/README.md
- operations/products.md
Added new operation products/getPricing
> Added products/getPricing

- _generator/config.yaml
- operations/currencies.md
> Migrate Currencies to MD generator

- _generator/config.yaml
- _generator/jsonschema.js
- _generator/naming.js
- operations/exchangerates.md
> Migrate Exchange Rates to MD generator

- _generator/config.yaml
- _generator/templates/parameters.edge
- _generator/templates/resource.edge
- operations/countries.md
> Migrate countries for docs generator

- _generator/jsonschema.js
- _generator/schema.js
- operations/exchangerates.md
- operations/images.md
> Fix enums handling with allOf, regenerate affected docs

- _generator/config.yaml
- _generator/jsonschema.js
- _generator/overrides.yaml
- _generator/page.js
- _generator/schema.js
- operations/_objects.md
- Deduplicate schemas on page
- Add more shared types' overrides
- Move Profile Data to shared types
> Generator improvements

- _generator/config.yaml
- operations/accountnotes.md
> Migrate account notes to docs generator

- _generator/jsonschema.js
- _generator/page.js
- _generator/schema.js
- _generator/sorting/schemaSort.js
- _generator/utils.js
- operations/accountnotes.md
- Rewrite links conversion to be more generic
- Remove x-ref-name
- Fix slugify for titles with brackets (ie. version suffixes) 
> CON-2322: Improve relative links conversion, further fixes

- changelog/README.md
- operations/reservations.md
> Added SendEmail to cancel reservation

- operations/reservations.md
Sort manually maintained Reservations reference page by the order of operations in the output file. This is only preparation to make changes to Reservations more diffable.
> CON-2240: Sort reservations documentation (no changes)

- changelog/README.md
- operations/payments.md
This PR adds documentation for the [new ghost payment data](https://github.com/MewsSystems/mews/pull/56016).
> Ghost payment data

- _generator/config.yaml
- _generator/sorting/operationSort.js
- _generator/types.yaml
- operations/_objects.md
- operations/reservations.md
> CON-2240: Migrate reservations to docs generator

- changelog/README.md
- deprecations/README.md
- operations/README.md
- operations/restrictions.md
* Deprecated 'Add restrictions' and 'Delete restrictions'
> Deprecated 'Add restrictions' and 'Delete restrictions'

- SUMMARY.md
- changelog/README.md
- concepts/README.md
- concepts/restrictions.md
- operations/restrictions.md
- use-cases/revenue-management.md
* Added new page `Restrictions` under `Concepts`
* Content about restrictions algorithms moved from `Operations > Restrictions` to `Concepts > Restrictions`
* Updated `Revenue management` use case accordingly
* This change is needed to prepare for automation of `Operations > Restrictions`, it's also a better design!
> Moved restrictions content from API Operations to Concepts

- changelog/README.md
- operations/orderitems.md
- operations/services.md
Regenerate reference docs using the current develop OAS.
> Synchronize reference docs

- _generator/types.yaml
- operations/availabilityadjustments.md
[mews.atlassian.net/browse/CON-2197](https://mews.atlassian.net/browse/CON-2197): Migrate Availability Adjustments
> CON-2197-Migrate-Availability-Adjustments-vol2

- _generator/config.yaml
- _generator/types.yaml
- operations/vouchers.md
https://mews.atlassian.net/browse/CON-2256: Migrate Vouchers page
> CON-2256 Migrate Vouchers

- changelog/README.md
- operations/payments.md
This PR adds documentation for the new `Type` property of `Invoice payment data`. Related PR: https://github.com/MewsSystems/mews/pull/56729.
> Invoice payment type

- _generator/config.yaml
- _generator/types.yaml
- operations/outletitems.md
https://mews.atlassian.net/browse/CON-2230 Migrate Outlet Items
N/A
N/A
> CON-2230 Migrate Outlet Items

- _generator/config.yaml
- _generator/types.yaml
- operations/exports.md
https://mews.atlassian.net/browse/CON-2219 Migrate exports
> Migrating exports

- _generator/config.yaml
- _generator/types.yaml
- operations/tasks.md
Migrating documentation for Tasks
> CON-2252 Migrate Tasks

- changelog/README.md
- operations/customers.md
> Add PreferredLanguageCode for customers/getall

- _generator/types.yaml
- changelog/README.md
- operations/availabilityadjustments.md
- operations/bills.md
- operations/cancellationpolicies.md
- operations/exports.md
- operations/orderitems.md
- operations/outletitems.md
- operations/reservations.md
- operations/services.md
- operations/vouchercodes.md
- operations/vouchers.md
Refs: CON-3438, CON-1629, CON-3377, CON-3381.
Looks like the changes to companions resulted in some missing descriptions.
> Regenerate documentation + update changelog

- changelog/README.md
- deprecations/README.md
- operations/companies.md
> Deprecate ElectronicInvoiceIdentifier

- _generator/types.yaml
- operations/services.md
> CON-3655: Handle Localized text

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/agecategories.md
https://mews.atlassian.net/browse/CON-2196 Migrating Age Categories
> Migrating Age Categories

- changelog/README.md
- guidelines/requests.md
- guidelines/responses.md
- Add success response codes to response codes list
- Document Prefer header in request.
> Document 204 response code

- changelog/README.md
- operations/vouchercodes.md
> Mark VoucherIds required

- changelog/README.md
- guidelines/environments.md
We have removed ClientToken level rate limitis
> Remove ClientToken rate limit

- _generator/config.yaml
- _generator/types.yaml
- operations/accountingcategories.md
https://github.com/MewsSystems/mews/pull/58872 Migrate Account Categories
> Migrating Accounting Categories

- _generator/config.yaml
- _generator/types.yaml
- operations/products.md
> Products documentation

- operations/accounts.md
Only sort accounts.md, no content changes.
> CON-2194: Sort accounts reference for automatic docs gen

- _generator/config.yaml
- _generator/types.yaml
- operations/rategroups.md
Updated documentation via automatic generation
> Rate Groups documentation

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/accounts.md
- operations/companies.md
> CON-2194: Migrate accounts for docs generator

- _generator/types.yaml
- changelog/README.md
- operations/README.md
- operations/cancellationpolicies.md
Update of the cancellation policies connector api documentation:
- New operation documentation: Get cancellation policies by **rates** operation.
- Update of the response model for Get cancellation policies by **reservations** operation.
> Update of the cancellation policies connector api documentation

- changelog/README.md
- operations/customers.md
> Add companyId for customers/add

- _generator/config.yaml
- _generator/types.yaml
- operations/restrictions.md
> Automative generated docs for Restrictions

- operations/restrictions.md
Move delete operation before set operation
> Move delete operation

- _generator/types.yaml
- changelog/README.md
- deprecations/README.md
- operations/accounts.md
- operations/agecategories.md
- operations/bills.md
- operations/orderitems.md
- operations/rates.md
- operations/reservations.md
- operations/services.md
- operations/vouchers.md
Reran docs generator with the develop + changes in https://github.com/MewsSystems/mews/pull/60319 and did my best to update the changelog.
I've intentionally omitted Restrictions file due to open PR: #661.
> Regenerate reference docs

- _generator/jsonschema.js
- _generator/types-resolver.js
- _generator/types.yaml
- changelog/README.md
- operations/_objects.md
- operations/restrictions.md
> Add hybrid identifier

- changelog/README.md
- operations/reservations.md
> CON-4292 Update Documentation to add ScheduledEndUtc  filter for reservations/getAll

- changelog/README.md
- operations/bills.md
> Con-4165:Add "Bill Name" to bills/getAll response documentation

- changelog/README.md
- getting-started/README.md
- operations/configuration.md
- operations/enterprises.md
Auto-updated `configuration.md` and manually updated `enterprise.md` to add the new `GroupNames` property in the response.
> MMP-8076: Added GroupNames to Enterprise

- changelog/README.md
- operations/accountingcategories.md
- operations/accountnotes.md
- operations/accounts.md
- operations/agecategories.md
- operations/availabilityadjustments.md
- operations/bills.md
- operations/cancellationpolicies.md
- operations/orderitems.md
- operations/outletitems.md
- operations/products.md
- operations/rategroups.md
- operations/reservations.md
- operations/resourcecategories.md
- operations/restrictions.md
- operations/services.md
- operations/tasks.md
- operations/vouchercodes.md
- operations/vouchers.md
Regenerate docs from develop. This update omits the `rates` tag, since there's a new deprecation and I need to confirm with @jonas-paul whether this is ready to be published.
> Regenerate docs

- _generator/package-lock.json
- _generator/package.json
Update dependencies of docs generator. Notably, there's an updated version of oas which bumps dependency on vulnerable jsonpath-plus: https://github.com/MewsSystems/gitbook-connector-api/security/dependabot/4
> generator: Update dependencies

- changelog/README.md
- changelog/changelog2023.md
- operations/counters.md
This PR documents counter types that were missing so far.
> Add missing bill counter types

- _generator/types.yaml
- changelog/README.md
- operations/README.md
- operations/accounts.md
Adds documentation for newly added accounts/addFile endpoint
> add documentation for new accounts/addFile API endpoint

- operations/businesssegments.md
> Mark ServiceIds as optional in businessSegments/getAll

- _generator/config.yaml
- _generator/types.yaml
- operations/businesssegments.md
> Business segments auto generated

- operations/businesssegments.md
> Fix description

- operations/businesssegments.md
> Regenerated business segments

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- deprecations/README.md
- operations/README.md
- operations/customers.md
I have manually reordered operations, check [`842da6c` (#677)](https://github.com/MewsSystems/gitbook-connector-api/pull/677/commits/842da6c2eb6e87e6b9fe0fc3e061f09d26203bbe) for cleaner diff of `customers.md`.
> CON-2214: Generate Customers docs

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/configuration.md
- operations/enterprises.md
Regenerate enterprises and configuration files + `TaxIdentifier`
> Regenerate enterprises and configuration

- changelog/README.md
- operations/availabilityblocks.md
Manually adjusted, before it's migrated to automatic generation
> Add AvailabilityBlockNumber

- _generator/types.yaml
- changelog/README.md
- operations/README.md
- operations/products.md
- operations/rates.md
Added new "Update products pricing" and "Delete rates" operations.
> Added "Update products pricing" and "Delete rates" operations

- _generator/types.yaml
- changelog/README.md
- operations/README.md
- operations/rates.md
Added restricted rates/set endpoint. Related PR: https://github.com/MewsSystems/mews/pull/62694
> Add "Set rates" operation

- changelog/README.md
- operations/routingrules.md
- added new parameter AssignmentTargetType to routing rules add
- added new parameter AssignmentTargetType to routing rules update
> Routing rule - AssignmentTargetType documentation

- _generator/config.yaml
- operations/cashiers.md
> Migrating Cashiers

- changelog/README.md
- operations/reservations.md
https://mews.atlassian.net/browse/CON-4950
Please note `GroupId` in response displays as an empty Guid since corresponding property in 
the response object code is not nullable (so cannot display as null in the docs.)
> Added availabilityBlock filtering to reservations/getAll/2023-06-06

- _generator/config.yaml
- _generator/types.yaml
- operations/serviceordernotes.md
Generated documentation
- Blockquote on top of the page was moved to `serviceOrderNotes/getAll` description
> Service Order Notes - Generator

- changelog/README.md
- events/wh-general.md
Added new type of general webhook - **PaymentUpdated**
> Add PaymentUpdated webhook

- changelog/README.md
- operations/orderitems.md
Con 5228 add documentation for cancel order items endpoint
> CON-5228 add documentation for cancel order items endpoint

- events/wh-faq.md
> Fixed two broken links

- operations/reservations.md
Update deprecation text for old reservation endpoint.
> Update deprecation text for reservations

- changelog/README.md
- operations/payments.md
Extended `payments/getAll` with `AccountIds`
> Add AccountIds filtering for payments/getAll

- changelog/README.md
- operations/resourceaccesstokens.md
Extended `resourceAccessTokens/update` with `Value` property
> Added Value for resourceAccessTokens/update

- changelog/README.md
- operations/payments.md
> CON-5700 add API documentation for creditCards/disable endpoint 

- changelog/README.md
- operations/payments.md
Reverts MewsSystems/gitbook-connector-api#733
> Revert "CON-5700 add API documentation for creditCards/disable endpoint "

- changelog/README.md
- operations/README.md
- operations/reservations.md
> CON-5791 Add documentation for reservations/getChannelManagerDetails end point

- changelog/README.md
- operations/reservations.md
> CON-5841 Generate documentation for ActualEndUtc filter in reservations/getAll ver 2023-06-06

- changelog/README.md
- operations/availabilityadjustments.md
* Follow-up to MewsSystems/mews#64957
* Solves https://mews.atlassian.net/browse/OPS-23442
> Add FirstTimeUnitReleaseUtc to AvailabilityAdjustment

- _generator/config.yaml
- operations/departments.md
https://mews.atlassian.net/browse/CON-2215 - Migrate Departments
> Regenerated Departments.md

- changelog/README.md
- operations/companies.md
> CON-5881-API Docs Update descriptions for Company Identifier field

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/cashiertransactions.md
https://mews.atlassian.net/browse/CON-2203 Migrating Cashier Transactions
> Migrating Cashier Transactions

- SUMMARY.md
- changelog/README.md
- deprecations/README.md
- deprecations/migration-guide-get-reservations.md
> Add migration guide for Get all reservations

- changelog/README.md
- operations/reservations.md
> Con 6135 update documentation for reservations/get channel manager details 

- changelog/README.md
- guidelines/responses.md
These are only documentation changes, no changes to the API
- Introduction of 404
- Adjusted 500 to 5xx to cover multiple codes that can happen
> Added 404 and adjusted 5xx

- operations/commands.md
Just manually reorder operations in `commands.md` as preparation for follow-up PR.
> CON-2204: Manually sort commands.md

- _generator/types.yaml
- changelog/README.md
- deprecations/migration-guide-get-reservations.md
- operations/README.md
- operations/availabilityadjustments.md
- operations/bills.md
- operations/creditcards.md
- operations/customers.md
- operations/orderitems.md
- operations/payments.md
- operations/products.md
- operations/rates.md
- operations/reservations.md
- operations/serviceordernotes.md
Collect all updates which weren't propagated earlier.
Should be merged after https://github.com/MewsSystems/mews/pull/66581 and https://github.com/MewsSystems/gitbook-connector-api/pull/752.
Also covers docs for CON-5058.
> Regenerate documentation

- changelog/README.md
- changelog/changelog2024.md
* Updated all changelog entries to the current format for 2025 and 2024, highlighting the affected API Operations.
> Updated all 2025 and 2024 changelog entries to the current format.

- changelog/README.md
- concepts/restrictions.md
* Added clarification to Concepts > Restrictions > Scope of restrictions.
* Clarification is the assumption that only one third-party integration manages restrictions for an enterprise.
* Jira [TW-67](https://mews.atlassian.net/browse/TW-67)
[TW-67]: https://mews.atlassian.net/browse/TW-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added clarification to Scope of restrictions.

- _generator/package-lock.json
- changelog/README.md
- operations/customers.md
Added CreatorProfileId and UpdaterProfileId to multiple customer endpoints
Also updated package-lock to newest version
> CreatorProfileId and UpdaterProfileId added

- changelog/README.md
- operations/configuration.md
- operations/enterprises.md
Added HoldingKey and ChainName to `enterpises/getAll` and `configuration/get`
> HoldingKey and ChainName

- _generator/types.yaml
- changelog/README.md
- operations/README.md
- operations/rates.md
> Add rates/updateCapacityOffset endpoint

- changelog/README.md
- operations/reservations.md
> CON-7567: Document ChannelManagerGroupNumber

- changelog/README.md
- guidelines/responses.md
Added Request-Id header and RequestId in Error Response Object
> RequestId header and in response

- changelog/README.md
- operations/README.md
- operations/commands.md
Fixed docs for fiscalMachineCommands/getAll
> CON-7684: Document fiscalMachineCommands/getAll

- _generator/types.yaml
- changelog/README.md
- operations/rates.md
- operations/reservations.md
- operations/vouchers.md
- Distinguish two variants of "Base rate pricing parameters"
- Add missing changelog
- Move "Rate for extent" to `reservations.md` where it is directly referenced (it's not used anywhere in `rates.md`)
> Fix rates/set docs

- changelog/README.md
- operations/reservations.md
> CON-7970: Fix reservation State description

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/counters.md
> CON-2209: Migrate Counters

- operations/agecategories.md
- operations/productcategories.md
- operations/serviceoverbookinglimits.md
Addresses review comments for CON-2234, CON-2209, and CON-2221.
> Regenerate docs with minor fixes

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/outletbills.md
> CON-2229: Migrate outlet bills for docs generator

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/customers.md
- operations/preauthorizations.md
> CON-2233: Generate preauthorizations docs

- changelog/README.md
- operations/exports.md
Updated documentation for API export file URLs
> Update documentation for API export file URLs

- operations/resourcefeatures.md
Just a manual reordering of resource features operations for cleaner merge in https://github.com/MewsSystems/gitbook-connector-api/pull/815.
> CON-2244: Reorder resource features

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/companionships.md
> CON-2206: Generate companionships from OAS

- _generator/config.yaml
- _generator/types.yaml
- operations/_objects.md
- operations/availabilityadjustments.md
- operations/customers.md
- operations/resourcefeatures.md
- operations/serviceoverbookinglimits.md
- operations/vouchercodes.md
- operations/vouchers.md
Beside regenerating resource features, I also fixed casing for activity states and moved Resource feature classification to resource features.
> CON-2244: Generate resource features from OAS

- _generator/config.yaml
- _generator/types.yaml
- operations/creditcards.md
- operations/payments.md
> CON-2211: Generate credit cards reference from OAS

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/messages.md
> CON-2225: Generate messages docs from OAS

- changelog/README.md
- operations/resourcecategories.md
Added ordering to resourceCategoryImageAssignments/getAll
> Regenerated resource categories

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/loyaltymemberships.md
- operations/loyaltyprograms.md
- operations/loyaltytiers.md
Also extended shared LP list, so had to regenerate other loyalty-related examples.
> CON-2223: Generate loyalty programs from OAS

- _generator/config.yaml
- _generator/types.yaml
- changelog/README.md
- operations/accountingitems.md
No significant changes beside Created / Updated / profile IDs and Identifier which went undocumented since '23. However I won't mention it in the changelog since it's a deprecated endpoint.
> CON-2192: Generate accounting items from OAS

- _generator/types.yaml
- changelog/README.md
- operations/creditcards.md
Add portfolio access token support for creditCards/addTokenized
> CreditCards add tokenized - portfolio access token support

- SUMMARY.md
- _generator/types.yaml
- changelog/README.md
- operations/README.md
- operations/_objects.md
- operations/ledgerbalances.md
Not marked as restricted, it has been in prod since April 2024.
> Generate ledger balances from OAS
