guidelines.md, operations/README.md, operations/finance.md, operations/reservations.md, operations/services.md
```
* Extended [API](guidelines.md#language-and-culture) parameters with optional `Language` and `Culture`.
* Added [Get all credit cards by ids](operations/finance.md#get-all-creditc-cards-by-ids) operation.
* Added [Get all credit cards by customers](operations/finance.md#get-all-creditc-cards-by-customers) operation.
* Extended [Accounting item](operations/finance.md#accounting-item) with `CreditCardId`.
* `Expiration` is optional in [Credit card parameters](operations/finance.md#credit-card-parameters). 
* Extended [Update reservation requested category](operations/reservations.md#update-reservation-requested-category) with `Overbook`.
* Extended [Add reservation product](operations/reservations.md#add-reservation-product) with `UnitCost`.
* Extended [Product …
```
=> May Connector extensions

operations/enterprises.md
```
* Extended [Space category](operations/enterprises.md#space-category) with `Names`, `ShortNames` and `Descriptions`.
```
=> Space category translations.

operations/finance.md, operations/services.md
```
* Extended [Add credit card payments](operations/finance.md#add-credit-card-payment) parameters with `AccountingCategoryId`.
* Extended [Add external payment](operations/finance.md#add-external-payment) parameters with `AccountingCategoryId`.
* Extended [Add outlet bills](operations/finance.md#outlet-item-parameters) parameters with `AccountingCategoryId`.
* Extended [Add order](operations/services.md#add-order) parameters with `AccountingCategoryId`.
```
Accounting CategoryId should be preferred way how to assign the category.
Accounting Category parameters are deleted from documentation.
=> Accounting Category Id

webhooks.md
Hi - we have just received our first webhook from Mews marketplace and we noticed that the payload we received was not matching the description in this page. Additionally the requestor was null
```
```
=> Reflect production webhook structure

operations/reservations.md
`[TDR-1765](https://mews.myjetbrains.com/youtrack/issue/TDR-1765): Attach credit card to reservation in Connector`
Accompanying gitbook PR to main mews repository PR #14858
* Added optional parameter `CreditCardId` for Reservation object in `/api/connector/v1/reservations/add`
* Added optional parameter `CreditCardId` for Reservation update object in `/api/connector/v1/reservations/update`
=> Attach credit card to reservation in Connector

operations/finance.md
The `UnitAmount` parameter definition linked to output DTO definition instead of input one (`TaxValues` instead of `TaxCodes`) .
=> outletBills/add fix DTO definition

operations/enterprises.md
[TDR-1783](https://mews.myjetbrains.com/youtrack/issue/TDR-1783)
```
* Extended `tasks/add` operation with optional parameter `ServiceOrderId`. This can be used to link task with a reservation.
```
=> Add task to reservation

operations/services.md
```
* Restricted [Update rate price](operations/services.md#update-rate-price) operation to accept only future updates and past updates within `EditableHistoryInterval`.
```
=> Past price updates not allowed

operations/finance.md
```
* Extended [Get all bills](operations/finance.md#get-all-bills) parameters with `ClosedUtc`, `CreatedUtc`, `DueDateUtc` and `PaidUtc` time filters.
```
=> New time filter format for bills/getAll

operations/configuration.md, operations/customers.md, operations/enterprises.md
```
* Renamed [Address](operations/configuration.md#address) input object to [AddressParameters](operations/customers.md#addressparameters), no parameters have been changed.
* Extended [Address](operations/configuration.md#address) output object with `Latitude` and `Longitude`.
```
=> Add geo location to configuration/get response

operations/finance.md
```
* Extended [Get all outlet items](operations/finance.md#get-all-outlet-items) parameters with `ClosedUtc` and `ConsumedUtc` time filters.
```
=> New time filters outletItems/getAll

operations/services.md
```
* Extended [Get all restrictions](operations/services.md#get-all-restrictions) parameters with `CollidingUtc`, `CreatedUtc` and `UpdatedUtc` time filters.
```
=> New time filter format for restrictions/getAll

operations/enterprises.md
```
* Extended [Get all space blocks](operations/enterprises.md#get-all-space-blocks) parameters with `CollidingUtc`, `CreatedUtc` and `UpdatedUtc` time filters. 
```
=>  New time filters spaceBlocks/getAll

operations/reservations.md
```
* Extended [Get all reservations](operations/reservations.md#get-all-reservations) parameters with 'GroupIds'.
```
=> GroupIds added

operations/services.md
* Extended [Get all restrictions](https://mews-systems.gitbook.io/connector-api/operations/services#get-all-restrictions) & [Add restriction](https://mews-systems.gitbook.io/connector-api/operations/services#add-restrictions) with `ExternalIdentifier`.
=> external identifier added to restrictions

operations/customers.md, operations/enterprises.md, operations/reservations.md, operations/services.md
```
A month ago we announced the [project Spacetime](https://developers.mews.com/project-spacetime/) whose main objective is to generalize the notion of services and spaces. And later, also the time units. We're pleased to announce that the first phase is now available in the Connector API. We're deprecating lot of things, we're generalizing spaces into resources, we're introducing the possibility to have multiple "visit" services, not just a single one etc. There are no breaking changes in the API, all of the previous endpoints and capabilities are still working and will be working until the end of the deprecation period. However we'd like to ask you to migrate as soon as possible, we're not able to roll out the new possibilities to our clients if you are not ready. If we did that, it …
```
=> multiple services

operations/reservations.md
```
* Fixed filtering by `ReservationIds` in [Get all reservations](operations/reservations.md#get-all-reservations) operation.
```
=> Fixed filtering for reservations/getAll

operations/reservations.md
```
* Fixed spelling mistake in parameter `TravelAgencyId` in operation [Update reservation](operations/reservations.md#update-reservation) (parameter `TraveAgencyId` will be deprecated).
```
=> fix typo TravelAgencyId

operations/finance.md
None. Just fixed the example for `bills/close` and added description for responses.
=> Finance fix error

operations/reservations.md, operations/services.md
```
* Extended operations [Add reservations](operations/reservations.md#add-reservations), [Add reservation product](operations/reservations.md#add-reservation-product) and [Add order](operations/services.md#add-order) with possibility to specify consumption date for products charged `Once` and `Per Person`.
```
=> Consumption date for charged once and per person

operations/customers.md, operations/reservations.md
```
* Replaced `Gender` property with `Sex` for operations [Add customer](operations/customers.md#add-customer), [Update customer](operations/customers.md#update-customer), [Get all customers](operations/customers.md#get-all-customer), [Search customers](operations/customers.md#search-customers) and [Get all reservations](operations/reservations.md#get-all-reservations) and all other usages.
```
=> replace Gender property with Sex

operations/services.md
Mixed use of H3 and H4 for some object/type descriptions, should be H4. 
We use this documentation to generate a proper API specification, this is the reason for this PR
=> Use consistency in headings

operations/services.md
=> fix typo in tax rate hyperlink in orders/add

changelog.md
Due to some partners' questioning the change log and now involving some of our clients trying to push blame, I've made a small clarification on the deprecation announcement from July 2nd.
Due to the discussions about the frequency of breaking changes, I would also like to remove the date from the deprecation highlight until we have finalised what breaking changes we will push to partners and when. Because if it is not functionally changing anything for us, like it did for Spacetime, I am finding it extremely hard to explain why we are asking them to invest more time into small changes, and I am getting a lot of push-back
Simply changed a couple of sentences
=> Update changelog.md for clarifications

use-cases/point-of-sale.md
- unified caps/small letters on outlets and orders
- included specific instruction on how rebate items should be sent (in addition to the endpoints to use)
- added link to help guide about outlets
```
```
=> fix typo and rebate instructions

operations/finance.md
The old description was wrong. It was suggesting that integration partners use this endpoint to record a payment taken through a terminal - which is confusing now that Mews has its own Terminal solution for which payment items are automatically generated via the Add Terminal Payment operation.
```
```
=> update Add Credit Card Payment endpoint description

guidelines/requests.md
Everywhere else in the documentation, platform address refers to the api.mews-demo or mews.li address for sending API requests, and MewsWebApplicationAddress for the URL used to log into Mews PMS (app.mews-demo or mews.li). 
This was the last place where it was different
rest of the gitboook
```
```
=> platform vs api address naming

operations/finance.md
Type is a required field for payments/addExternal when pushing information to the properties based in the French Legal Environment. unspecified is considered as fraud
```
```
=> payments/addExternal Update for French Properties

operations/customers.md, operations/services.md
```
* Added [Get Deleted Customers](operations/customers.md#get-all-customers) filtering with `DeletedUtc`.
* Filtering by `DeletedUtc` is only enabled when [Activity States](operations/customers.md#activity-state) field is provided as `Deleted` or `All`.
```
=> Add filtering on customers/getAll for deleted customer

operations/services.md
integration partners don't realise that to send a "rebate", they cannot send a negative "count" x positive "amount" (and must send positive "count" x negative "amount". Specifying the accepted range of values to prevent questions from integration partners.
```
```
=> specify number value requirements in orders add

operations/customers.md, operations/finance.md, operations/reservations.md, use-cases/event-management.md
```
*  Replaced `Accounting item` with [Order item](operations/finance.md#order-item) and [Payment item](operations/finance.md#payment-item) in [Get all reservations](operations/reservations.md#get-all-reservations), [Get all reservation items](operations/reservations.md#get-all-reservation-items), [Get customers open items](operations/customers.md#get-customers-open-items), [Update accounting items](operations/finance.md#update-accounting-items), [Get all bills](operations/finance.md#get-all-bills), [Close bill]((operations/finance.md#close-bill)  operations.
```
=> Replace references to Accounting items

operations/enterprises.md
Added missing property 'CompanyId' to companies/update
```
```
=> Small fix to add missing property to companies/update (YT RND-33462)

operations/services.md
```
* Extended [Time unit period](operations/services.md#time-unit-period) with Month.
* Added [Time unit](operations/services.md#time-unit).
* Extended [Get rate pricing](operations/services.md#get-rate-pricing) with FirstTimeUnitStartUtc, LastTimeUnitStartUtc and info about max interval length.
* Extended [Get rate pricing](operations/services.md#get-rate-pricing) return value with TimeUnitStartsUtc
* Removed DatesUtc from [Get rate pricing](operations/services.md#get-rate-pricing) return value
* Extended [Update rate price](operations/services.md#update-rate-price) with FirstTimeUnitStartUtc, LastTimeUnitStartUtc and info about max interval length.
* Removed TimeUnit from [Bookable service data](operations/services.md#bookable-service-data)
* Added TimeUnitPeriod to [Bookable service …
```
=> Rates endpoint - TimeUnit interval

operations/reservations.md
```
* Extended operations [Get all reservations](../operations/reservations.md#get-all-reservations) with `OrderItems` in `ReservationExtent` to prevent double serialization of Items.
```
=> Add OrderItems to ReservationsExtent

operations/messages.md, operations/messagethreads.md
```
* Extended operations [Get all messages](../operations/messages.md#get-all-messages) with `Limitation` to provide a pagination functionality
* Extended operations [Get all message threads](../operations/messagethreads.md#get-all-message-threads) with `Limitation` to provide a pagination functionality
```
=> Added limitation to message and message-threads

operations/creditcards.md
ObfuscatedNumber property was removed for addTokenized endpoint.
```
* [ObfuscatedNumber](../operations/creditcards.md#add-tokenized-credit-card) property removed.
```
=> Update creditcards.md - ObfuscatedNumber removed

operations/restrictions.md
```
* Updated `Days` field of [Restriction conditions](../operations/restrictions.md#restriction-conditions) to optional.
```
=> Made restriction Days optional.

operations/availabilityblocks.md
```
* Removed StartUtc and EndUtc from [Availability block parameters](operations/availabilityblocks.md#availability-block-parameters).
* Added FirstTimeUnitStartUtc and LastTimeUnitStartUtc to [Availability block parameters](operations/availabilityblocks.md#availability-block-parameters).
* Removed StartUtc and EndUtc from [Availability block update parameters](operations/availabilityblocks.md#availability-block-update-parameters).
* Added FirstTimeUnitStartUtc and LastTimeUnitStartUtc to [Availability block update parameters](operations/availabilityblocks.md#availability-block-update-parameters).
```
=> Update availability block parameters by timeunits

changelog/README.md, operations/bills.md
Added purchase order number to bills
=> PurchaseOrderNumber

changelog/README.md, operations/README.md, operations/commands.md
* Ref. YT kanban-4667 "Document: Add payment terminal command"
* Added new operation 'Add payment command'
* This needs verification from the Connectivity Team! In particular, the definition of Amount is NOT consistent with Amount used in the Mews Payment Terminals use case (PR #394)
=> added new restricted operation 'Add payment command'

changelog/README.md, guidelines/serialization.md, operations/restrictions.md
Important changes to address errors from misuse of restrictions endpoints:
* Re-wrote **Datetime** section in **Serialization** page to better explain date-time formats and how they should be used, including examples
* Numerous small updates to the **Restrictions** page to clarify use of `StartUtc` and `EndUtc` and correct minor issues
=> important re-working of Datetime documentation and restrictions page

operations/reservations.md
Type used for the request is int not string
=> Set type to int instead of string

SUMMARY.md, changelog/README.md, operations/_objects.md, operations/accountingitems.md, operations/addresses.md, operations/availabilityadjustments.md, operations/availabilityblocks.md, operations/bills.md, operations/cashiertransactions.md, operations/companies.md, operations/companionships.md, operations/companycontracts.md, operations/customers.md, operations/loyaltymemberships.md, operations/loyaltyprograms.md, operations/messages.md, operations/messagethreads.md, operations/outletitems.md, operations/rates.md, operations/reservations.md, operations/resourceaccesstokens.md, operations/resourceblocks.md, operations/resources.md, operations/restrictions.md, operations/routingrules.md, operations/services.md, operations/sourceassignments.md, operations/sources.md, operations/tasks.md
* Added new page 'Common objects' under Operations
* Removed all duplicate instances of common object definitions, like `time interval` and `string update value`
* Updated all references to point to the common objects
In due course I will update the Style Guide to describe the change in policy.
=> added new Common objects page

changelog/README.md, operations/reservations.md
Fixed mistake in parameter name in `reservations/cancel`.
=> Reservation cancel parameter name fix

changelog/README.md, operations/rules.md
Extended `rule-conditions` in `rules/getall` with `TravelAgencyId`.
=> Add travel agency id to rules/getall

changelog/README.md, operations/orderitems.md, operations/payments.md
The orderItems/getAll and payments/getAll endpoints are the first to receive multi-property support. I did not make any specific descriptions of multi-property access in this PR, suggestions welcome.
=> add EnterpriseIds for orderItems/getAll and payments/getAll

changelog/README.md, operations/orderitems.md
Some endpoints include now "Creator Profile" and "Updater Profile" in the response. This is already displayed in the code example in the documentation, but not explained. I noticed it also in bills/getAll. Can we please add an explanation to all endpoints that return those values?
=> Add CreatorProfile & UpdaterProfile explanation in orderitems.md

changelog/README.md, operations/loyaltymemberships.md
Added `CreatorProfile` and `UpdaterProfile` to the `LoyaltMembership` object. `ProfileData` will show the type of profile in `Discriminator,` and the `ProfileId` in `EnterpriseProfile`. For non-enterprise profiles, `LoyaltyMembership` will not show any data, and `EnterpriseProfile` object will be null.
=> LoyaltyMembership CreatorProfile and UpdaterProfile

operations/_objects.md, operations/agecategories.md, operations/rates.md
* Corrected reference to `Localized text` in agecategories.md
* Corrected reference to `Localized text` in rates.md
* Updated definition of `Localized text`, including example JSON
* Probably doesn't need a Changelog entry
=> improvements to localized text

operations/services.md
This endpoint is used to fetch all services from Mews. It doesn't make sense to make Service Ids a required field, because those values are not known when using this endpoint.
`ServiceIds` should be an optional parameter when calling services/getAll.
=> Update ServiceIds to optional, not required

changelog/README.md, operations/reservations.md
Added `CommanderOrigin` to the response for endpoint `reservations/getall/2023-06-06`.
=> Commander origin

changelog/README.md, deprecations/README.md, operations/reservations.md
As a follow-up to #489, we're marking `StartUtc` as deprecated in favor of more explicit fields. No discontinuation date has been set for the time being.
=> CON-228: Mark StartUtc as deprecated

changelog/README.md, deprecations/README.md, operations/reservations.md
StartUtc had an undocumented behavior: when guest checked-in earlier before the original StartUtc, the time of reservation would change to this time. Some partners relied on this behavior, until it was unintentionally changed by separating out `StartUtc` to `StartedUtc` property. `StartUtc` now holds the scheduled time of reservation, and `StartedUtc` holds the actual, check-in time.
We've recovered this original behavior and added two new properties which expose the raw values:
- `ActualStartUtc` is mapped to `StartedUtc`
- `ScheduledStartUtc` is mapped to unmodified `StartUtc`.
=> CON-152: reservations/getAll: Update StartUtc docs, add ScheduledStartUtc and ActualStartUtc

changelog/README.md, deprecations/README.md, operations/bills.md
=> Deprecated extent in bills/getAll

operations/products.md
In the documentation, we still call the pricing part "UnitAmount" even though it was replaced by "Price" and "Pricing".
Can we please add all the necessary documentation as per swagger?
=> Change UnitAmount to Price in products.md

changelog/README.md, operations/orderitems.md
Since OrderItems allows filtering by ServiceId, we should also expose the property in the response object.
=> CON-705: Add ServiceId to OrderItems

operations/bills.md
Fix invalid JSON and null property in JSON example for `bills/getAll` response.
Follow up to #517.
=> OPS-2882: bills/getAll response - fix JSON example

changelog/README.md, operations/resourceblocks.md
Expose `Name` and `Notes` in `resourceBlocks/getAll`. Apparently we allowed for setting these with `add`, but never exposed them.
=> CON-675: Add Name and Notes to resourceBlocks/getAll

changelog/README.md, deprecations/README.md, operations/configuration.md, operations/enterprises.md
Replace EditableHistoryInterval property with separate accounting and operational history interval properties.
=> Replace EditableHistoryInterval property

operations/reservationgroups.md
* I assume the duplicate EnterpriseId in 'Get all reservation groups' was added in error, so I have removed it
* The change occurred as part of the work to support Portfolio Access Tokens (21st June 2023, to be precise)
* I have not added a Changelog entry as this is just a minor bug fix
=> De-duplicate EnterpriseId in Get all reservation groups

operations/reservations.md
The more generic "account Id" has replaced "company Id" and "customer Id" in some newer endpoints. 
Currently, accounts can only be customers. In the future, also companies might fall under accounts. See the slack conversation for more details.
To avoid confusion, I've updated the definition to make it clear which data can be expected in accountId. This might also need to be updated in other endpoints that reference accountId.
=> Better explanation of accounts

changelog/README.md, operations/README.md, operations/_objects.md, operations/services.md
Document new `services/getAvailability/2024-01-22`.
Marked as restricted for the time being, so not marking the previous version deprecated (and once we get to that point, it'd be pretty straightforward to cover this with migration guide).
=> CON-1137: Add Get service availability (ver 2024-01-22)

operations/accounts.md
Quick fix to correct heading level for 'Account type' definition
* Changed `Account type` from heading-3 to heading-4 in the Accounts page
* Also removed unhelpful Company and Customer links within the `Account type` definition
* Also added '`' characters, following standard convention for string enumerations in the docs
=> Update accounts.md (quick fix)

deprecations/README.md
Remove previously announced discontinuation dates for mappings related to company billing (mostly).
=> Remove discontinuation dates for mappings

changelog/README.md, deprecations/README.md, operations/reservations.md
Introduce `ActualEndUtc` and `ScheduledEndUtc` and deprecate `EndUtc`
=> Introduce ActualEndUtc and ScheduledEndUtc

operations/bills.md
The current description of Receipt is not correct, because the bill can be only the Receipt or Invoice and with current description there is a blank spot. The endpoints returns even bills type of Receipt which has not been full paid.
This discrepancy is probably coming from the report, where it shows only closed bills (which means they have been paid).
This is suggestion of description.
=> Bill type description correction

operations/cashiertransactions.md
Cashiertransactions/getAll never had filtering by `CreatedUtc` but it's `UpdatedUtc`
=> Cashier transaction fix parameter

operations/resources.md
Small fix to make the documentation match the example within the same file.
I believe `ResourceIds` is an array of strings, not a string.
=> Update ResourceIds Property Type for "Get all resources" Request

_generator/overrides.yaml, _generator/page.js, _generator/schema.js, _generator/utils.js, operations/_objects.md, operations/accountnotes.md, operations/countries.md, operations/currencies.md, operations/devices.md, operations/exchangerates.md, operations/images.md, operations/orderitems.md
https://mews.atlassian.net/browse/CON-2227
A few changes to the generator logic:
- make URLs which point to `operations` pages relative
- add ordering for properties and schemas
- show common schemas in the response section
This PR also includes specific ordering for order item properties in order to get clearer diff with the previous version. The ordering is removed in a subsequent [PR](https://github.com/MewsSystems/gitbook-connector-api/pull/598).
=> Migrate order items to docs generator

changelog/README.md, operations/productserviceorders.md
=> Extended product service orders with linked reservation id.

README.md, SUMMARY.md, changelog/README.md, changelog/changelog2022.md, concepts/README.md, concepts/time-units.md, getting-started/README.md, guidelines/README.md, operations/availabilityadjustments.md, operations/availabilityblocks.md, operations/products.md, operations/rates.md
* Added new top-level section `Concepts`
* Added new page `Time units` under `Concepts`
* Changed all references to `services/time-units`, **EXCEPT** those within `services.md`, to point to the new page
* Minor tweaks to home page and Guidelines as a result of the new section
* The contents of the `Concepts` section will be developed further in future
* This change to be implemented in conjunction with PR #600 
=> New section Concepts and Time units

_generator/.editorconfig, _generator/jsonschema.js, _generator/page.js, _generator/template-schema.js, _generator/templates/deprecatedProperty.edge, _generator/templates/resource.edge, _generator/types.d.ts, operations/services.md
=> Expose deprecationMessage in reference docs

operations/_objects.md
* Minor tweaks to **Common objects** (documentation-only):
* Removed bogus description from `ProfileData`
* Changed `ProfileDataDiscriminator` to `Profile data discriminator`
* Corrected heading level for `Currency value (ver 2018-06-07)`
=> Small tweaks to Common objects

_generator/config.yaml, _generator/types.yaml, operations/_objects.md, operations/cancellationpolicies.md
https://mews.atlassian.net/browse/CON-2201:  Migrate Cancellation Policies documentation
- Implemented automatic documentation generation for the cancellation policy endpoint
- Generated the cancellation policy page
=> CON-2201 Migrate Cancellation Policies documentation

SUMMARY.md, changelog/README.md, operations/loyaltyprograms.md, use-cases/README.md, use-cases/how-to.md, use-cases/loyalty.md
* Added new use case **Customer loyalty**
* Added 13 new 'how to' use cases related to **Customer loyalty**
* Documentation-only, no changes to API functionality
* Additionally, removed `DataClusterId` from Loyalty program parameters as advised by @VBuben
=> Added new use case Customer loyalty

operations/rates.md
https://mews.atlassian.net/browse/CON-2238: Sort the Rates page manually according to the generated Rates page so its easier to compare generated page
=> CON-2238-Migrate-Rates-Manual-Sort

changelog/README.md, changelog/changelog2023.md, operations/availabilityblocks.md
https://mews.atlassian.net/browse/OPS-18782 Add Connector API documentation for missing AvailabilityBlock fields
Solves https://mews.atlassian.net/browse/CON-3730
Adds documentation for previously missing fields along with fields added in https://github.com/MewsSystems/mews/pull/57422
=> OPS-18782 Add Connector API documentation for missing AvailabilityBlock fields

operations/availabilityblocks.md
This issue was reported by RevControl. They mentioned that the current explanation doesn’t fully capture what actually happens, and they provided the below example to clarify.
{
"Id": "e19297af-373e-4701-b4ea-afae0129bded",
"AvailabilityBlockId": "aaaa654a4a94-4f96-9efc-86da-bd26d8db",
"ResourceCategoryId": "1268c440-21c5-415d-bf58-ac87008b2bda",
"FirstTimeUnitStartUtc": "2021-10-14T00:00:00Z",
"LastTimeUnitStartUtc": "2021-10-17T00:00:00Z",
"UnitCount": 6,
"ActivityState": "Active",
"UpdatedUtc": "2021-10-21T13:32:32Z"
}
The 6 rooms allocated on October 14th released on October 13th The 6 rooms allocated on October 15th released on October 14th The 6 rooms allocated on October 16th released on October 15th The 6 rooms allocated on October 17th released on October 16th
I did some testing …
=> Improve description of RollingReleaseOffset

operations/outletbills.md
the parameter Type is required and not optional as the documentation mentions. https://mews.slack.com/archives/C01TCGUJ5FV/p1728999190267759
=> Fix Type in outletbills/add

SUMMARY.md, _generator/config.yaml, _generator/types.yaml, changelog/README.md, operations/README.md, operations/serviceoverbookinglimits.md
Generate docs for Service overbooking limits.
=> Add service overbooking limits docs

_generator/types.yaml, changelog/README.md, operations/vouchers.md
Increased AssignedRateIds to 10
=> Increased AssignedRateIds to 10

_generator/sorting/operationSort.js, operations/accounts.md, operations/bills.md, operations/cancellationpolicies.md, operations/customers.md, operations/reservations.md
- Adjust sorting to group all add* operations. Sort `addFile` operations below update operations
- Regenerate docs, excluding:
- Rates
- Source assignments, since regeneration reverts changes in https://github.com/MewsSystems/gitbook-connector-api/pull/682
- Request examples no longer include null values (this is change in OAS)
No changelog updates it seems.
=> Improve sorting + regenerate docs

_generator/types.yaml, operations/reservations.md, use-cases/events.md
Raised by TPSM: Links to Product order parameters from Reservations were incorrect. I also manually fixed link from Events.
=> Fix links to Product order parameters

_generator/types.yaml, changelog/README.md, operations/rates.md
Add backwards compatible hybrid identifier for "Update rate price".
=> Add hybrid identifier for "Update rate price"

_generator/template-schema.js, operations/accounts.md, operations/bills.md, operations/customers.md
Clarify usage of Title prefix enum and pull it into Customers resource.
Changes in the generator are related to adjustments in schema generation: I added explicit `x-showDescription` extension for enums, to distinguish when to render descriptions, as on most places we are just replicating the property description.
=> CON-4203: Improve + fix Title enum docs

changelog/README.md, operations/payments.md
* improved `payments/refund` endpoint description
* updated `payments/refund` response example to include `Status`
=>  Improved `payments/refund` description in docs

operations/README.md
Those endpoints are not restricted, we just forgot to remove word restrictions from the operations table
=> Remove restricted from operations table

changelog/README.md, deprecations/README.md, operations/configuration.md, operations/enterprises.md
- Added `Address` to the enterprises/getAll
- Removed deprecation of a property, it can remain
=> Address for enterprises/getAll and removed deprecation

changelog/README.md, deprecations/README.md, operations/commands.md
- Deprecating CustomerId and FullName in PaymentTerminalCommandData 
- Making `CustomerId` as non required, breaking change introduced by https://github.com/MewsSystems/mews/pull/61938/files and replaced with `AccountId` and `AccountData`
=> Add documentation for payment terminal command data change

_generator/types.yaml, changelog/README.md, operations/accountnotes.md, operations/accounts.md, operations/addresses.md, operations/bills.md, operations/companies.md, operations/identitydocuments.md, operations/payments.md, operations/products.md, operations/reservations.md, operations/serviceoverbookinglimits.md, operations/vouchercodes.md, operations/vouchers.md
Following files were omitted from regeneration: Age Categories, Customers, Order Items, Rates
Addresses CON-5530, CON-5410. Reverts CON-5206.
=> Regenerate docs

changelog/README.md, operations/companycontracts.md
Updated description of companyContracts/delete to include reference to Portfolio Access Tokens.
Updated the change log
=> Con 5226 make company contracts delete multiproperty

changelog/README.md, operations/customers.md
set title and sex as optional in `Customers/Update `endpoint
=> CON-5778 Sex Field in Customers/update should be marked as Optional

changelog/README.md, guidelines/requests.md
Enforcing address to exactly match how it's described in the docs
=> Enforcing exact address

_generator/types.yaml, deprecations/migration-guide-get-reservations.md, operations/reservations.md
Old "Service order state (ver 2017-04-12)" used in `reservations/getAll` uses `Enquired`, but newer "Service order state" used in (apparently) all other operations uses `Inquired`.
=> Fix reservation State description

operations/bills.md
Follow up to https://github.com/MewsSystems/gitbook-connector-api/pull/750 – add examples for company billing data in bills responses.
I didn't update the changelog because this is non-functional, minor docs change worth documenting.
=> CON-5797: Improve examples for bill company data

changelog/README.md, operations/rates.md
Document `IsDefault` property in `rates/getAll`.
=> CON-7106: Expose IsDefault in rates/getAll

changelog/README.md, operations/bills.md
Extended Bill customer data used in Get all bills with new property.
=> CON-6558: Added TaxIdentifier to Bill customer data

changelog/README.md, operations/products.md
ProductClassifications are extended with new `Fee` value. Updating documents for it.
Change has just been merged to develop, will probably be available today afternoon / tomorrow morning.
=> Extend ProductClassifications with Fee

changelog/README.md, operations/reservations.md
Add TravelAgencyIds and CompanyIds req parameters to Get all reservations.
=> CON-6193: Add TravelAgencyIds and CompanyIds req parameters

_generator/types.yaml, changelog/README.md, operations/orderitems.md
Breaking changes that we need to discuss regarding extension of order items data with allowances data.
Added 2 new order item types for allowances (AllowanceLoss, AllowanceContraLoss).
Added 2 new values for discriminator of order item data related to allowances (AllowanceDiscount, AllowanceProfits).
Added 2 new dto's used for the new order item data discriminators.
Added enum for profits (AllowanceContraBreakage, AllowanceLoss, AllowanceContraLoss).
=> Order items extended with allowances data

_generator/collect-jsonschema.js, _generator/collect-schemas.js, _generator/index.js, _generator/jsonschema.js, _generator/page.js, _generator/template-schema.js, _generator/templates/parameters.edge, _generator/types.d.ts, _generator/types.yaml, operations/commands.md
Add support for polymorphic request body into generator. Also regenerated `commands.md` to show how it works with `fiscalMachineCommands/getAll`, but the docs here are incomplete (missing examples) – I will tackle that in a stacked PR, where I will also update the changelog.
Implementation-wise, I decided to create a separate method for handling request body with `oneOf` to avoid regressions, so this is currently treated as a special case.
The phrase "The operation supports the following mutually exclusive parameters." is hard-coded in the template. I tried to pass the description via OAS into the parent abstract class, but it replaced the descriptions' of derived concrete classes.
=> CON-7483: Generate docs for polymorphic requests

changelog/README.md
Forgot to update changelog in the last PR that added the `providerMembershipId` to membership update endpoint
=> CON-8032 Update changelog

_generator/types.yaml, changelog/README.md, operations/payments.md
Add PaymentOrigin enum to payments/getAll.
=> CON-8194: Add PaymentOrigin to payments/getAll

_generator/config.yaml, _generator/types.yaml, operations/reservationgroups.md
Only enable and regenerate docs for reservation groups, no changes to the contract.
=> CON-2239: Migrate reservation groups to docs generator

changelog/README.md, operations/availabilityblocks.md
Changes related to this task (https://mews.atlassian.net/browse/OPS-27544) involved updating the `"availabilityblocks/add"` endpoint to extend the request DTO with a new pickupDistribution option, enabling partners.
In this PR:
- Generated documentation for the new property in the `AvailabilityBlockAddParameters `DTO
- Add new entry to Changelog for this update
=> Generate new documentation for AvailabilityBlocks/add endpoint
